version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./etc/compose/src/Dockerfile
    image: tz-17-06/app:latest
    restart: unless-stopped
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./mounts/src/logs:/src/logs
      - ./mounts/src/static:/src/static
      - ./mounts/src/media:/src/media
    cap_add:
      - ALL
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:8000/" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  postgres:
    build:
      context: .
      dockerfile: etc/compose/postgres/Dockerfile
    image: lmschat/postgres:latest
    restart: unless-stopped
    volumes:
      - ./mounts/postgres/pg_data:/var/lib/postgresql/data
      - ./mounts/postgres/backups:/backups
      - ./mounts/postgres/logs:/var/log/postgresql
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - "${DB_PORT:-5432}"

